server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacy_warehouse
    username: postgres
    password: 1706
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
